name: Publish @juhwannn/ui

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 코드
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'

      - name: GitHub Packages 인증
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: 의존성 설치
        run: npm install

      - name: 라이브러리 빌드
        run: npm run build

      - name: GitHub Packages에 퍼블리시
        run: npm publish
